url: "https://www.aisparksstudio.com"
baseurl: ""
title: AI Sparks Studio &#124; Free, polished UI for your GPT-4 API access
masthead_title: AI Sparks Studio
name: Daniel Dorotík. AI Sparks Studio™ is a trademark of Daniel Dorotík
email: ai@aisparksstudio.com
description: >
  AI Sparks Studio is a free, user-friendly interface for your API access to top AI models like GPT-4 - a polished alternative to OpenAI Playground. Engage in expert discussions with capable AI models, have your speech converted to text using Whisper, and transform discussions into lifelike speech audio with the ElevenLabs service.
minimal_mistakes_skin: default
search: false
logo: "/assets/images/logo.webp"

atom_feed:
  hide: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: Europe/Prague

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Daniel Dorotík"
  avatar : "/assets/images/avatar.webp"
  bio    : "Author of AI Sparks Studio"

analytics:
  provider: "custom"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

sass:
  style: compressed # Optional: Change to 'expanded' for easier debugging