title: AI Sparks Studio - A neat User Interface for your state-of-the-art AI
masthead_title: AI Sparks Studio
name: Daniel Dorotík. AI Sparks Studio™ is a trademark of Daniel Dorotík
email: ai@aisparksstudio.com
description: >
  AI Sparks Studio is a user interface for state-of-the-art AI models. Engage in expert discussions with AI models like OpenAI's ChatGPT or GPT-4, convert speech to text using the Whisper model, and transform discussions into lifelike speech audio with the ElevenLabs service.
minimal_mistakes_skin: default
search: false
logo: "/assets/images/logo.webp"

atom_feed:
  hide: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: Europe/Prague

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Daniel Dorotík"
  avatar : "/assets/images/avatar.webp"
  bio    : "Author of AI Sparks Studio"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
